### ISSUE TITLE
fix the special character display issue

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#117]
- [ ] try to replace `coverage` with `album.title`
- [ ] artist name in the song title

TODO: add few examples from georgeblood
- [x] `Playing track - I&#39;ll Be Home For Xmas; Adeste Fidelis (O Come All Ye Faithful), USA` [from](https://archive.org/details/78_ill-be-home-for-xmas-adeste-fidelis-o-come-all-ye-faithful_ralph-berger-orch.-j_gbia0006792b)
- [x] `Playing track - Santa Claus Is Comin&#39; To Town, USA` [from](https://archive.org/details/78_santa-claus-is-comin-to-town_american-novelty-orchestra-gillespie-coots_gbia0006805b)
- [x] `Playing track - Red Streamliner &gt;, Davenport, IA, 1977` [from](https://archive.org/details/lf1977-04-23.aud.scooter123.goodyfixed.109349.sbeok.flac16)

btw google recommends to use app.data here https://developers.google.com/actions/dialogflow/tutorials/number-genie but as I see all text messages which are fallen there will be encoded by `RFC 3986` and in particular `I didn't` will become `I didn&#39;t`.

**Comment by mc2** [comment]
![quot](https://user-images.githubusercontent.com/20852/38711275-9e7c0426-3e79-11e8-9262-d507b5077a79.png)

It seems if there's no metadata.year, the JavaScript doesn't handle it gracefully
![nan](https://user-images.githubusercontent.com/20852/38711276-9ec4c9c2-3e79-11e8-84df-7a167959d254.png)

**Comment by hyzhak** [comment]
after all it was problem in song data processing - because speech uses SSML and requires escaping but display text doesn't need it. So I have just split song data to both stream speech and display text
