### ISSUE TITLE
cannot read property key of undefined

### ISSUE THREAD

**Issue by vegeta1509** [internetarchive/internet-archive-google-action#159]
![screen shot 2018-03-19 at 12 53 29 am](https://user-images.githubusercontent.com/26794179/37569992-18bff30a-2b10-11e8-88fa-9bd8957a0f73.png)
i'm getting this error can anyone help me

**Comment by hyzhak** [comment]
this is related issue https://github.com/internetarchive/internet-archive-google-action/issues/145
