### ISSUE TITLE
Improve welcome message

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#283]
Based on feedback from Alexa team:

> Either-or prompts often confuse users, as it can be hard to tell when one option ends and another begins. It’s not always clear to the user the skill is offering two options. Either-or questions should be used only for the simplest options, as users tend to answer “yes” or “no” to these prompts.
> - Instead of: “Welcome to music at the Internet Archive. Would you like to listen to music from our collections of 78s or Live Concerts?”
> - Try: “Welcome to Internet Archive music. You can listen to 78s or concerts; or ask me for an artist or genre. Which would you like to listen to?”

**Comment by adaveinthelife** [comment]
We attempted to make a change to the original dialog to reflect Alexa UI review but this caused some issues with the app's overall architecture. Instead we settled with making questions more clear and are currently working on making a help dialog.
