### ISSUE TITLE
add app icons to alexa skill

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#292]
added here:
https://developer.amazon.com/alexa/console/ask/publish/alexapublishing/amzn1.ask.skill.95aeada6-be8f-4740-ae9f-eb5ccb495ac0/development/en_US/skill-info

icons should be 108x108 pixels and 512x512 pixels

<img width="614" alt="screen shot 2018-07-19 at 14 07 31" src="https://user-images.githubusercontent.com/184706/42941447-1c9eab76-8b5d-11e8-9286-8a0ef739339b.png">

**Comment by adaveinthelife** [comment]
Icons have been added. Both small version and big one. Closing issue.
