### ISSUE TITLE
Add description of IA Alexa Skill

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#293]
source:
https://developer.amazon.com/alexa/console/ask/publish/alexapublishing/amzn1.ask.skill.fc01cf61-ad69-483f-a8ef-c94ff434a459/development/en_US/skill-info?

target:
https://developer.amazon.com/alexa/console/ask/publish/alexapublishing/amzn1.ask.skill.95aeada6-be8f-4740-ae9f-eb5ccb495ac0/development/en_US/skill-info

<img width="779" alt="screen shot 2018-07-19 at 14 06 41" src="https://user-images.githubusercontent.com/184706/42941408-01dacf90-8b5d-11e8-9719-03ae507a6afe.png">

**Comment by adaveinthelife** [comment]
Alexa skill is now available for Beta testing. Previous version invocation has been changed to "Internet Archive old" to differentiate versions. Closing issue.
