### ISSUE TITLE
Make Alexa Skill available for beta testing

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#294]
Here are options:

<img width="1015" alt="screen shot 2018-07-19 at 14 05 12" src="https://user-images.githubusercontent.com/184706/42941363-ce399234-8b5c-11e8-8a97-e3ca8c0edcfb.png">

But should finish the description of Alexa Skill 1st https://github.com/internetarchive/internet-archive-google-action/issues/293

**Comment by adaveinthelife** [comment]
Descriptions have been added and Alexa Skill has been sent out for Beta testing.
