### ISSUE TITLE
Version action keeps session open without prompt

### ISSUE THREAD

**Issue by adaveinthelife** [internetarchive/internet-archive-google-action#310]
Having had another review of our Alexa skill from Amazon, this was one of the issues they raised. This refers to the fact that the session (and the mic) stay open after someone asks for "version" which maps to our version action.

>After the skill completes a task, the session remains open with no prompt to the user. The skill must close the session after fulfilling requests if it does not prompt the user for any input.

Steps To Reproduce:

User: "Alexa open internet archive" 
Skill: "Welcome to music at the Internet Archive. You can listen to our collections of 78s or live concerts. Which would you like to listen to?" 
User: "tell me the version of app." 
Skill: "Version is 2.2.1.", and the session remains open.

**Comment by hyzhak** [comment]
Alexa team noted this problem again:

> Common issues observed on all Alexa devices
> After the skill completes a task, the session remains open with no prompt to the user. The skill must close the session after fulfilling requests if it does not prompt the user for any input.
> 
> Steps To Reproduce:
> 
> User: "Alexa open internet archive"
> Skill: "Welcome to music at the Internet Archive. You can listen to our collections of 78s or live concerts. Which would you like to listen to?"
> User: "tell me the version of app"
> Skill: "Version is 2.2.1.", and the session remains open.
