### ISSUE TITLE
JSDocs needed in mathjs extending modules

### ISSUE THREAD

**Issue by himanshuc3** [internetarchive/internet-archive-google-action#398]
Files: ```mathjs/includes.js``` and ```mathjs/equaljs```

**Comment by hyzhak** [comment]
what do you mean by that? Where do you need jsdocs in those files?

**Comment by himanshuc3** [comment]
the includes and equal function, there input and output. Also, I want to contribute but don't know where to start and how to get local development environment get going. Can you help?

**Comment by hyzhak** [comment]
@himanshuc3 you should start from reading README, especially this section https://github.com/internetarchive/internet-archive-google-action#how-to-make-contributions

**Comment by hyzhak** [comment]
@himanshuc3  I don't see any problems with JSDOC for those files, could you be more specific?
