### ISSUE TITLE
Catch all exceptions in action handlers and prompt user

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#45]
- [x] Catch all exceptions in action handlers
- [x] log errors
- [x] tell a user something like: 
> **IA:** Something went wrong. But will fix it very soon. Try to ask something like: play all albums of Grateful Dead.

**Comment by poush** [comment]
@hyzhak Are these exceptions are related with the situations where IA server isn't reachable or there can be more or all generic exceptions?

**Comment by hyzhak** [comment]
@poush it should handle any type of exceptions
