### ISSUE TITLE
expose version of the app to the logs on start

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#83]
should get the version from packages.json

**Comment by bimlendra** [comment]
@markjohngraham  has approved the question dialog for app version. So, this question will also be served in the scope against this ticket.

**Comment by bimlendra** [comment]
@hyzhak : I am writing code logic for version dialog. Should I still log it on start or just log the version when user ask for version?

**Comment by hyzhak** [comment]
Nothing is change - logging on start is the core feature. The app version on a user request is optional.
Btw could you finish other issues before this one?

**Comment by bimlendra** [comment]
@hyzhak : I need to create an intent for this in dialogflow. Please suggestm, if I can made this change?

**Comment by hyzhak** [comment]
@bimlendra sure, but can you finish other issues first?

**Comment by bimlendra** [comment]
As per my understanding, I have finished other issues. For process.env in uploader, I have left a question for you.

**Comment by hyzhak** [comment]
@bimlendra not yet, please take a look my comments

**Comment by bimlendra** [comment]
Done
